### ISSUE TITLE
QUESTION: Vue Integration?

### ISSUE THREAD

**Issue by JacobFJ** [williamjuan027/nativescript-ui-components#12]
Thanks, I love this directive...

**Comment by JacobFJ** [comment]
Image Zoom :)

**Comment by williamjuan027** [comment]
Thanks :)

I am currently moving the demo components that I have for my tutorials on nativescripting into a single Angular app (since they were all originally written for Nativescript Angular). I'm going to try to add core and vue integrations once I'm done with that.

**Comment by JacobFJ** [comment]
@williamjuan027 thank you so much! We will wait it :)
